### PR TITLE
Updated departmentMapping for RMP and departmentList specifically for…

### PR DESCRIPTION
**Pull request by AllenHsm**
… search by department

The search component on gold has two different methods: search by area / search by department. And the options are different for the two methods. So we need two different matching list for this two options.

### CODE REVIEW

**Review by xinyao-song — APPROVED** [review]
LGTM

**Comment by zhenbi93** [comment]
LGTM, merge it after merging Daniel's

**Review by zhenbi93 — APPROVED** [review]
LGTM

**Review by Division7 — APPROVED** [review]
LGTM 😎 🤙

**Pull request merged**
