### PR TITLE
Unit and Integration Tests with Jest

### PR DESCRIPTION
**Pull request by xinyao-song**
- Added unit and integration tests for individual app components.
- Added unit tests for the Login and Home screens.
Screenshot 2024-11-22 at 10 27 08 AM

### For more specific information, reference to each README.md below
**Daniel:** https://github.com/ucsb-cs184-f24/team04-GOLDTracker/blob/main/team/Division7/README.md
**Xinyao:** https://github.com/ucsb-cs184-f24/team04-GOLDTracker/blob/main/team/xinyao-song/README.md

### Additional Note:
- The modification of over 9,000 lines is a result of adding `yarn.lock` to `.gitignore`.
- You might encounter issues with watchman when you first try to run `npm test`
- Use Node.js ver. 20 for correct result

### CODE REVIEW

**Review by AllenHsm — APPROVED** [review]
LGTM

**Review by zhenbi93 — APPROVED** [review]
A Test not passed

**Review by zhenbi93 — CHANGES_REQUESTED** [review]
A test not pass

**Comment by xinyao-song** [comment]
> A test not pass

switch to node.js 20 by use nvm 20, that fixes the issue

**Comment by zhenbi93** [comment]
> > A test not pass
> 
> switch to node.js 20 by use nvm 20, that fixes the issue

Tested, LGTM 
截屏2024-11-22 下午10 39 15

**Review by zhenbi93 — APPROVED** [review]

**Pull request merged**
